### ISSUE TITLE
Proof

### ISSUE THREAD

**Issue by jwaterloo** [boost-ext/di#115]
In your library you state the following
- Reduce boilerplate code
- Reduce cost of maintenance effort
- Reduce testing effort
- Give better control of what and how is created
- Give better understanding about objects hierarchy

Could you provide comprehensive examples and explanation of sufficient length to demonstrate all of these advantages. [Along the lines of what is the forwarding problem and how r-value references and variadic templates provide the perfect forwarding needed to fix it. ... The thought is some may not understand the problem you are solving and how big of a problem it can be that demands that it be solved.]

**Comment by kris-jusiak** [comment]
Thanks for your feedback. Totally agree that those statements should be supported by examples and, therefore, documentation improvement is on my road map before version 1.0.0 and the official boost review. For now tho, I can refer you to some examples which are already written and hopefully that will help a bit:
- Reduce boilerplate code
  - You don't have to create all types on your own
    
    auto t1 = make_unique<T1>(deps...)
    auto t2 = make_unique<T2>(deps...)
    auto t3 = make_unique<T3>(deps...)
    auto t4 = make_unique<T4>(deps...)
    auto app = make_unique<App>(t1, t2, t3, t4);
    
    above boilerplate is reduced with di framework to simpler configuration
    (notice that order in which types are created is important and has to be maintained)
- Reduce cost of maintenance effort
  - changing constructor of a type won't require changing configuration
    
    some_class(unique_ptr<i1>, unique_ptr<i2>);
    some_class(unique_ptr<i1>, unique_ptr<i2>);
    
    both of above might be created with the same configuration, which wouldn't be the case
    without di framework
  - you don't have to maintain objects creation yourself, might be a pain, when dependencies order
    will change
- Reduce testing effort
  - DI itself helps with testing, but framework can make it even easier by automatic mocks injection:
    https://github.com/krzysztof-jusiak/di/blob/cpp14/example/extensions/providers/mocks_provider.cpp
    https://github.com/krzysztof-jusiak/mocks_injector
- Give better control of what and how is created
  - Scopes to define object life time (ex. unique, singleton or deduce(based on parameter type))
    https://github.com/krzysztof-jusiak/di/blob/cpp14/example/quick_user_guide/scopes1.cpp
    https://github.com/krzysztof-jusiak/di/blob/cpp14/example/quick_user_guide/scopes2.cpp
    https://github.com/krzysztof-jusiak/di/blob/cpp14/example/quick_user_guide/scopes3.cpp
    https://github.com/krzysztof-jusiak/di/blob/cpp14/example/quick_user_guide/scopes4.cpp
    https://github.com/krzysztof-jusiak/di/blob/cpp14/example/quick_user_guide/scopes5.cpp
  - Using policies you can limit types which might be created (for example only smart pointers)
    https://github.com/krzysztof-jusiak/di/blob/cpp14/example/custom_policy.cpp
  - Custom providers allow you to have common strategy of types creation
    https://github.com/krzysztof-jusiak/di/blob/cpp14/example/pool_provider.cpp
- Give better understanding about objects hierarchy
  - you can dump object creation graph
    https://github.com/krzysztof-jusiak/di/blob/cpp14/example/extensions/policies/uml_dumper.cpp
    https://github.com/krzysztof-jusiak/di/blob/cpp14/example/extensions/policies/types_dumper.cpp

P.S. although variadic templates and perfect forwarding is very useful it's possible to implement similar di library with C++98 standard, but compilation times are really poor then :/
https://github.com/krzysztof-jusiak/di/tree/cpp03

**Comment by kris-jusiak** [comment]
close it for now as there is no response in 18 days

**Comment by jwaterloo** [comment]
Thank you for taking the time to respond to me. It is greatly appreciated. Even more so when you make needed code or documentation adjustments. Sorry, I have not responded sooner. I am frequently pulled n many different ways.

I just found time to evaluate your latest documentation on http://krzysztof-jusiak.github.io/di/cpp14/boost/libs/di/doc/html/di/introduction.html and it is even better. Thank you! It actually feels like you listened too me. Following are some comments.

http://krzysztof-jusiak.github.io/di/cpp14/boost/libs/di/doc/html/di/introduction.html

In your first table after the "Hollywood principle" you have 3 column labels; "Let's make some coffee!", "No Dependency Injection" and "Dependency Injection".
While it is true that the "No Dependency Injection" has no DI it is equally true that "Dependency Injection" doesn't have it either. Revised labels and/or a description row under the labels MAY be in order. Let me explain. "No Dependency Injection" is bad coding, an anti-pattern as it were, were a coder has tied the implementation of coffee_maker to electric_heater and heat_pump instead of coding to interfaces, compile time or run time, as was done in "Dependency Injection". The "Dependency Injection" example doesn't use DI it is just coded properly and ready for it when upon use someone uses Boost.DI. This clarity may be essential to beginners.

In most if not all of the tables that have columns “Manual Dependency Injection” and “Boost.DI” it would be nice to have another column, the first column, as a graph diagram like you did in "Let's make some coffee!".

I was also confused by what “No changes!” meant as the “Manual Dependency Injection” clearly changed. It felt like there was something important there was being missed.

In “Boost.DI simplify testing” “Boost.DI” shouldn't it be “mi.create<coffee_maker>();”. Also I don't follow these latter examples as well as the earlier examples. I know it is a work in progress from the ???. I can't wait till it is complete.

**Comment by kris-jusiak** [comment]
Thank you for your time and feedback, it's always more than welcomed
I see your points, they are very valid and definitely will adopt the spec according to your suggestions!

Yea, documentation is far for being done yet, but I'm going to start working on it ASAP, I will let you know when it will be finished, hopefully still this month

Thanks again!
