### ISSUE TITLE
Creation of empty injector crashes on MSVC 2015, Update 1, x64, Debug

### ISSUE THREAD

**Issue by VladimirZhilyakov** [boost-ext/di#211]
This code crashes on MSVC 2015, Update 1, x64, Debug

```
#include "di.hpp"
int main() {
    auto injector = boost::di::make_injector(); // Read access violation
    //boost::di::make_injector(boost::di::bind<X>()); // Ok: non-empty injector
    return 0;
}
```

x32 or Release work fine
It's reproducible on both 1.0.0 and master branch

**Comment by kris-jusiak** [comment]
Thank you @VladimirZhilyakov for reporting this! Should be fixed by https://github.com/boost-experimental/di/commit/9d13ee681619c6d9bd83f82729f34ff1d2836c20. The appveyor build was always testing using 32 bits, cheers again, great job :+1:
