### ISSUE TITLE
Link error if di.hpp is included in two cpp-files

### ISSUE THREAD

**Issue by VladimirZhilyakov** [boost-ext/di#212]
Steps to reproduce:

1) Create a project and add two cpp-files to it

```
#include "di.hpp"
int main() { return 0; }
```

```
#include "di.hpp"
void f() {}
```

2) Compile the project

Actual result: link error
LNK2005 "class &lt;lambda&gt; boost::di::v1_0_0::detail::make_injector" already defined in main.obj

Environment: MSVC 2015 Update 1

**Comment by kris-jusiak** [comment]
Thank you @VladimirZhilyakov for reporting this! Should be fixed by https://github.com/boost-experimental/di/commit/9d13ee681619c6d9bd83f82729f34ff1d2836c20. The appveyor build was always testing using 32 bits, cheers again, great job :+1:
