### ISSUE TITLE
Unexpected destructor invocation

### ISSUE THREAD

**Issue by sdoiel61** [boost-ext/di#218]
I'm learning about Boost DI.
In an effort to learn I took one of the examples from the tutorial and added output instructions to the constructors and destructors of most objects:

namespace di = boost::di;

```
struct renderer
{
    int device;
};

class view
{
public:
    view( std::string /*title*/, const renderer& )
    {
        tout << __FUNCSIG__ << std::endl;
    }
    ~view() { tout << __FUNCSIG__ << L" view" << std::endl; }
};

class model
{
public:
    model()
    {
        tout << __FUNCSIG__ << std::endl;
    }
    ~model() { tout << __FUNCSIG__ << L" model" << std::endl; }
};

class controller
{
public:
    controller( model&, view& )
    {
        tout << __FUNCSIG__ << std::endl;
    }
    ~controller() { tout << __FUNCSIG__ << L" controller" << std::endl; }
};

class user
{
};

class app
{
public:
    app( controller&, user& )
    {
        tout << __FUNCSIG__ << std::endl;
    }
    ~app() { tout << __FUNCSIG__ << L" app" << std::endl; }
};
```

The main test object contains:
void CBoostDiTest::RunTest()
{
    tout << **FUNCSIG** << std::endl;

```
auto injector = di::make_injector();
injector.create<app>();
```

}

The output:
void __thiscall CBoostDiTest::RunTest(void)
__thiscall `anonymous-namespace'::view::view(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,const struct`anonymous-namespace'::renderer &)
__thiscall `anonymous-namespace'::model::model(void)
__thiscall`anonymous-namespace'::controller::controller(class `anonymous-namespace'::model &,class`anonymous-namespace'::view &)
__thiscall `anonymous-namespace'::app::app(class`anonymous-namespace'::controller &,class `anonymous-namespace'::user &)
__thiscall`anonymous-namespace'::app::~app(void) app
__thiscall `anonymous-namespace'::app::~app(void) app
__thiscall`anonymous-namespace'::app::~app(void) app
__thiscall `anonymous-namespace'::app::~app(void) app

It looks like 4 distinct objects are being constructed but the destructor of one of the objects is being invoked 4 times.

**Comment by kris-jusiak** [comment]
Thanks @sdoiel61 for the question. Your observations are correct. `app` dtor will be called more times because it's created by copy in this case, so it's not the destructor of the same object being called many times but it's for a different copy.

``` cpp
injector.create<app>(); // copy here
```

You can check it out by adding prints for copy/move constructors.

``` cpp
   app(const app&) { tout << __FUNCSIG__ << L" app" << std::endl; } // copy ctor
   app(app&&) { tout << __FUNCSIG__ << L" app" << std::endl; } // move ctor
```

If you want to avoid copying of `app` you can create it by ref of rvalue

``` cpp
injector.create<app&>();
injector.create<app&&>();
```

**Comment by sdoiel61** [comment]
Thank you.

Next question:

The “app” object gets destroyed, but how do I eliminate those instances of “view”, “model”, and “controller” that were created automatically?

I’m using VS2015 and intellisense tells me nothing about operations that I might perform on the injector to clean up.  I’m kind of new to the fancy use of templates that are used by boost.di.

Regards,
Steve

**Comment by kris-jusiak** [comment]
Di will take care of cleaning everything for you, that's one of the reason for using it not to worry about the memory.

With Boost.DI life time of objects depends on the scope which by default is deduced accordingly to the parameter type - http://boost-experimental.github.io/di/user_guide/index.html#di_deduce. So in this case `view` and `model` is a reference, hence singleton scope will be used by default (meaning that instances will be destroyed with the app). You can change the scope by changing the parameter type. For example, if you change `model&` to let's say `unique_ptr<model>` or just `model`, unique scope will be used and you will get a different object each time constructor will be called. You can also change the scope explicitly when binding.

``` cpp
di::bind<model>.in(di::unique); // or any other scope you want
```

You can also write your own scope if the ones provided don't satisfy your needs. Boost.DI extensions has 3 additional scopes: 'scoped', 'shared' and 'session'. You can check them out here: http://boost-experimental.github.io/di/extensions

**Comment by sdoiel61** [comment]
Thank you for your patience.  And your work.

Regards,
Steve
