### ISSUE TITLE
Adding of mutex class member make an errors of compilation.

### ISSUE THREAD

**Issue by Kroll** [boost-ext/di#223]
I just add a class member of std::mutex and g++ prints some errors to me.

Example of code:

```
#include <memory>
#include <mutex>

#include "di.hpp"
namespace di = boost::di;

using namespace std;

using namespace std;

class A
{
public:
    A(int i/*, int ii*/) : m_i(i) {/*m_i = ii;*/} //Uncomment ii comments to remove an error messages from compilation.
private:
    int m_i;
    std::mutex m_m; //This line goes to error! Appears with single argued constructor, not with zero or double argued;
};

class B
{
public:
    B(std::shared_ptr<A> a) : m_a(a) {}
private:
    std::shared_ptr<A> m_a;
};

int main()
{
    auto in = di::make_injector();

    auto b = in.create<B>();

    return 0;
}
```

Compilation errors:

> g++ -c -m64 -pipe -g -std=c++1y -Wall -W -fPIC  -I../di-mutex -I. -I../../boost -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o main.o ../di-mutex/main.cpp
> ../di-mutex/main.cpp: In function 'int main()':
> ../di-mutex/main.cpp:32:27: error: 'T boost::di::v1_0_1::core::injector<TConfig, boost::di::v1_0_1::core::pool<boost::di::v1_0_1::aux::type_list<> >, TDeps ...>::create() const [with T = B; typename boost::di::v1_0_1::aux::enable_if<(! boost::di::v1_0_1::core::injector<TConfig, boost::di::v1_0_1::core::pool<boost::di::v1_0_1::aux::type_list<> >, TDeps ...>::is_creatable<T, boost::di::v1_0_1::no_name, boost::di::v1_0_1::aux::integral_constant<bool, true> >::value), int>::type <anonymous> = 0; TConfig = boost::di::v1_0_1::config; TDeps = {}]' is deprecated: creatable constraint not satisfied [-Werror=deprecated-declarations]
>      auto b = in.create<B>();
>                            ^
> In file included from ../di-mutex/main.cpp:4:0:
> ../../boost/di.hpp:2417:3: note: declared here
>    create
>    ^
> ../../boost/di.hpp: At global scope:
> ../../boost/di.hpp:963:4: error: inline function 'static T\* boost::di::v1_0_1::concepts::type<T>::has_to_many_constructor_parameters::max<TMax>::error(boost::di::v1_0_1::_) [with int TMax = 10; T = A]' used but never defined [-Werror]
>     error(_ = "increase BOOST_DI_CFG_CTOR_LIMIT_SIZE value or reduce number of constructor parameters");
>     ^
> cc1plus: all warnings being treated as errors
> Makefile:365: recipe for target 'main.o' failed
> make: **\* [main.o] Error 1

**Comment by kris-jusiak** [comment]
Thanks @Kroll for reporting the issue.

Your issue should be soled on master by https://github.com/boost-experimental/di/commit/a809130c23bb1996d1a9a8bd8c9fbc3e75e01a82, however, it's not yet released.

You can check it online here: http://melpon.org/wandbox/permlink/sG3XQkBy2mAZ5vET

I can keep this issue open till the new version won't be released.
