### ISSUE TITLE
Using DI for creating objects further in runtime

### ISSUE THREAD

**Issue by Shelim** [boost-ext/di#225]
DI is very good at resolving dependency tree during application startup. However I can't find in documentation ways to dynamically create objects during runtime with resolver. Consider:

```
class irenderer
{
public:
    virtual ~irenderer() { }
    virtual void render() = 0;
}
class renderer
{
public:
    void render() final { /* render */ }
}
class state
{
public:
    virtual ~state() { }
}
class state_menu : public state
{
public:
    state_menu(std::shared_ptr<irenderer> rend) { rend->render();  }
}
class framework
{
private:
    std::unique_ptr<state> state
public:
     void change_state(std::unique_ptr<state> state)
     {
         this->state = std::move(state);
     }
     void run()
    {
         for(;;)
        {
             if(  /* some elaborate condition */ )
                    // how can I create state_menu here with resolving depedencies?
                    // note: I might need to create state_menu outside of this class!
                    // this->change_state(new state_menu()); 
         }
     }
}
void main()
{
    auto injector = di::make_injector(  di::bind<irenderer>().to<renderer>()  );
    auto framework = injector.create<std::shared_ptr<framework> >();
    framework->run();
}
```

**Comment by kris-jusiak** [comment]
Thanks @Shelim for the question.

Well, you have a few ways of dealing with it. You will defo have to pass an object into a framework which will create a state_menu for you. Right now, depening on whether you want to inject all objects into state_menu using DI or if you want to pass some parameters yourself you have the following options.
* provider (no parameters will be passed, new object will be created)
* smart factory (you can choose which parameters should be injected and which you will pass but they have to be in order), new object will be created)
* assisted injection (you can choose which parameters (named = assisted) will be injected by di and which you will pass, new object will be created)
1. Use a provider
```cpp
class framework {
private:
  std::unique_ptr<state> state_;
  provider<std::unique_ptr<state_menu>> sm;

public:
  explicit framework(provider<std::unique_ptr<state_menu>> sm) : sm(sm) {}

  void change_state(std::unique_ptr<state> state) { state_ = std::move(state); }

  void run() {
    for (;;) {
      if (true /* some elaborate condition */) {
        this->change_state(sm.get());
      }
    }
  }
};
```
Example here -> http://boost-experimental.github.io/di/extensions/index.html#lazy

2. Use a smart factory

```cpp
class framework {
private:
  std::unique_ptr<state> state_;
  const ifactory<state_menu> &sm;

public:
  explicit framework(const ifactory<state_menu> &sm) : sm(sm) {}

  void change_state(std::unique_ptr<state> state) { state_ = std::move(state); }

  void run() {
    for (;;) {
      if (true /* some elaborate condition */) {
        this->change_state(sm.create());
        break;
      }
    }
  }
};

int main() {
  // clang-format off
  const auto injector = di::make_injector(
     di::bind<irenderer>().to<renderer>()
   , di::bind<ifactory<state_menu>>().to(factory<state_menu>{})
  );
  // clang-format on
  auto f = injector.create<std::shared_ptr<framework>>();
  f->run();
}
```
Example here -> http://boost-experimental.github.io/di/extensions/index.html#factory

3. Use assisted injection
Example here -> http://boost-experimental.github.io/di/extensions/index.html#assisted-injection

I hope that helps a bit.

**Comment by Shelim** [comment]
I think I missed a very important thing in my description: the states are provided by framework's users, not by framework itself. Regarding that I have no way of telling which arguments from framework they need, which arguments they need on they own, or even how many of different states descendants exists at all

**Comment by kris-jusiak** [comment]
I'm not sure whether I get it. How are users defining states? (by type?, by string?, by xml?) Can you elaborate, please? Some example would be extremely handy as well. Thanks.

**Comment by Shelim** [comment]
Sorry for delay, I was a few days away from world;

I mean something like that: http://pastebin.com/8UW11fFQ

But I actually managed to write workaround, that satisfy my needs, so this
remains pure academic :)

2017-01-29 23:15 GMT+01:00 Kris Jusiak <notifications@github.com>:

**Comment by kris-jusiak** [comment]
Glad to hear that you have found a wknd!

Anyway, frankly speaking, I'm still not sure whether I understand your problem correctly.
For my current understanding, though, your example it's a perfect fit for a smart factory mentioned before in this thread.

**Comment by Shelim** [comment]
Hello!

You're right, smart factory is in fact the solution I need, I was probably
too tired to understand the flow in the first place :-)

Thanks!
Piotr

2017-02-05 21:56 GMT+01:00 Kris Jusiak <notifications@github.com>:
