### ISSUE TITLE
Unable to compile with VS 2017 RC, VS 2015 works fine

### ISSUE THREAD

**Issue by jhruby** [boost-ext/di#226]
struct  app_context
   {
      auth::authentication_service& authentication_service;
   };   

auto injector = di::make_injector(
      di::bind<auth::authentication_service>().to<auth::impl::authentication_service>()   );

   auto app_context = injector.create<web::app_context>();

I am using compiler switch /std:c++14 and X64 build.

C:\workspaces\closure.web\src\libs\di-cpp14\include\boost\di.hpp(1842): error C2248: 'boost::di::v1_0_0::scopes::deduce::scope<TExpected,TGiven>::is_referable<const closure::auth::authentication_service&>': cannot access private member declared in class 'boost::di::v1_0_0::core::dependency<TScope,TExpected,T,TName,TPriority>'

**Comment by jhruby** [comment]
Did actually someone read this issue?

**Comment by ColinDuquesnoy** [comment]
I am facing the same issue with VS 2017 Community Edition.

**Comment by kant2002** [comment]
@kris-jusiak Any news on this ?

**Comment by nesteruk** [comment]
Same issue here!

**Comment by kris-jusiak** [comment]
I believe it should be fixed by https://github.com/boost-experimental/di/commit/fe57643272804d8d713de6abeada4afd9a953278?

**Comment by kris-jusiak** [comment]
Fixed and verified by appveyor -> https://ci.appveyor.com/project/krzysztof-jusiak/di/history
