### ISSUE TITLE
Fail: Test number 138: test.ft_di_errors

### ISSUE THREAD

**Issue by fgenolini** [boost-ext/di#228]
Hi,

The test fails when run from the build directory, but passes when run from the source.

System:
MacBookPro, OSX 10.12.4, clang from XCode, cmake-gui 3.8.0

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ --version
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Repro:
* Extract di into ~/Projects/di/
* mkdir ~/Projects/di-build/
* cd ~/Projects/di/
* cmake-gui
* select the ~/Projects/di/ as the source and ~/Projects/di-build/ as th build folder
* select all the defaults in cmake (Makefile, default system compiler...)
* cd ~/Projects/di/ && make
  * all builds successfully
  * all tests are run and all pass
* cd ~/Projects/di-build/ && make
  * all builds successfully
  * tests are not run
* cd ~/Projects/di-build/ && make test
  * all tests run
  * test number 138 fails (all the tests from error109.cpp to error164.cpp fail with the same error)

Here is the error from the test logs:

```
error164.cpp:1:10: fatal error: 'boost/di.hpp' file not found
#include <boost/di.hpp>
         ^~~~~~~~~~~~~~
1 error generated.
clang++ -I../include -I../../include -std=c++1y  -Werror error164.cpp 2> error164.out
~/Projects/di/test/ft/di_errors.cpp:99:false
```

The include path is incorrect for this test.
The test can be made to pass by fixing the include path or copying the entire include folder to the build folder.

**Comment by kris-jusiak** [comment]
Fixed in master.
