### ISSUE TITLE
destructor called twice on classes created with injector.create<T>

### ISSUE THREAD

**Issue by roland-wolf** [boost-ext/di#231]
// Destructor in hello_world example was running twice. Here is a stripped down example. 
//Run this code and watch the output

#include <iostream>
#include <boost/di.hpp>

namespace di = boost::di;

struct helloWorld {
    helloWorld()
    {
        std::cout << "constructor " << this << std::endl ;
    }

    ~helloWorld()
    {
        std::cout << "destructor " << this << std::endl ;
    }

    void run() const
    {
        std::cout << "running " << this << std::endl ;
    }
};

int main()
{
    {
        std::cout << "--------------boost di object creation--------------"  << std::endl;
        auto injector = di::make_injector();
        auto hello = injector.create<helloWorld>();
        hello.run();
    }

    {
        std::cout << "--------------standard object creation--------------"  << std::endl;
        helloWorld hello;
        hello.run();
    }
    return 0;
}

/* The output will look like this
--------------boost di object creation--------------
constructor 0x7ffeca0f8a97
destructor 0x7ffeca0f8a97
running 0x7ffeca0f8ab7
destructor 0x7ffeca0f8ab7
--------------standard object creation--------------
constructor 0x7ffeca0f8ab7
running 0x7ffeca0f8ab7
destructor 0x7ffeca0f8ab7

We see that instances created with injector.crate<T>() are created in one place, destructed, moved to another place (this pointer changed), and then destructed again. This is very puzzling and would exclude di from certain use cases.
*/

**Comment by skyrpex** [comment]
You are creating an instance of helloWorld and using the copy constructor. Hence, you see two destructor calls.
```cpp
int main()
{
std::cout << "--------------boost di object creation--------------" << std::endl;
auto injector = di::make_injector();
// Copy constructor called. Also, one helloWorld gets destroyed.
auto hello = injector.create<helloWorld>();
hello.run();
}
```

Try creating a unique_ptr instead. It'll just call one destructor:

```cpp
auto hello = injector.create<std::unique_ptr<helloWorld>>();
hello->run();
```

**Comment by roland-wolf** [comment]
Yes, with a unique_ptr it works perfectly. We are having a workaround now. However I still find it strange that not using unique_ptr results in one constructor and two destructors. This is not the expected behaviour when making a copy. This should be fixed, at least it should be explained in the documentation what is going on.

**Comment by skyrpex** [comment]
There's nothing to add to the documentation: that's pretty basic C++ knowledge. You should read about how copy constructors (and copy assignment operators) work.

Just to clarify what's happening, try this code using the [try-online thingy](http://boost-experimental.github.io/di/try_it/index.html):

```cpp
#include <iostream>
#include <boost/di.hpp>

namespace di = boost::di;

struct helloWorld {
    helloWorld()
    {
        std::cout << "constructor " << this << std::endl ;
    }
  
    // This is what you're missing there.
    helloWorld(const helloWorld&)
    {
        std::cout << "copy constructor" << this << std::endl ;
    }
    
    ~helloWorld()
    {
        std::cout << "destructor " << this << std::endl ;
    }
    
    void run() const
    {
        std::cout << "running " << this << std::endl ;
    }
};

int main()
{
    {
        std::cout << "--------------boost di object creation--------------" << std::endl;
        auto injector = di::make_injector();
        auto hello = injector.create<helloWorld>();
        hello.run();
    }
    
    {
        std::cout << "--------------standard object creation--------------"  << std::endl;
        helloWorld hello;
        hello.run();
    }
    return 0;
}
```

Running the code will output this:
```
Running... [OK]
--------------boost di object creation--------------
constructor 0x7ffc8d3a8830
copy constructor0x7ffc8d3a8828
destructor 0x7ffc8d3a8830
running 0x7ffc8d3a8828
destructor 0x7ffc8d3a8828
--------------standard object creation--------------
constructor 0x7ffc8d3a8830
running 0x7ffc8d3a8830
destructor 0x7ffc8d3a8830
```

**Comment by roland-wolf** [comment]
Thanks, I missed the auto-generated copy-constructor.

**Comment by skyrpex** [comment]
Cool! I'm sorry, I was a bit rude
