### ISSUE TITLE
Check for __make_integer_seq without depending on __has_builtin

### ISSUE THREAD

**Issue by andreadps** [boost-ext/di#232]
Not that I am proud of it, but I need to use more than 10 parameters in a certain constructor. Setting `BOOST_DI_CFG_CTOR_LIMIT_SIZE` breaks the compilation on VS 2015. It fails on `make_index_sequence`.

I found that `make_index_sequence_impl` can be set either manually (for 0, 1, ... or 10 arguments) or automatically. The later only happens if `__has_builtin(__make_integer_seq)` is true. However, although the VS 2015 compiler supports `__make_integer_seq`, `__has_builtin` does not exist.

Would there be a way to check on `__make_integer_seq` without depending on Clang's  `__has_builtin` ?

**Comment by kanstantsin-chernik** [comment]
@andreadps not sure that I understand what you said here. But generally if you need more then 10 params just declare typedef:
```
struct ClassWithLongConstructor
{
        ClassWithLongConstructor(int, double, shared_ptr<interface>);
        using boost_di_inject__ = boost::di::inject<int, double, shared_ptr<interface>>; 
}
```
