### ISSUE TITLE
Problems compiling with _GLIBCXX_DEBUG defined

### ISSUE THREAD

**Issue by gajanak** [boost-ext/di#235]
If _GLIBCXX_DEBUG is defined, compiling with gcc 7.1 results in something like :

`error: reference to 'vector' is ambiguous`

sample:

```c++
#define _GLIBCXX_DEBUG 
#include <boost/di.hpp>

#include <string>
#include <vector>

std::vector<std::string> m_params;

int main() {
}

```

Reason is the fwd declaration in di.hpp line 83-98 which doesnt match to the debug Version of STL coming with gcc.

```
template <class, class>
class vector;
```

I reproduced this with gcc 7.1.0 from https://wandbox.org/#  .

Hope this helps someone else too.

**Comment by kris-jusiak** [comment]
Fixed by https://github.com/boost-experimental/di/pull/259
