### ISSUE TITLE
Support for decorator pattern

### ISSUE THREAD

**Issue by ColinDuquesnoy** [boost-ext/di#252]
What is the proper way to use boost-di with the [decorator pattern](https://en.wikipedia.org/wiki/Decorator_pattern#UML_class_and_sequence_diagram)?

How to actually tell boost-di how to map several implementations to the same interface without each decorator to know about the next decorator and how to specify the decorator order? Is there something like ``when_injected_into<T>``?

**Comment by kanstantsin-chernik** [comment]
@ColinDuquesnoy Hi. I don't think Boost DI has anything ready to use. But probably annotations or factory extension can help you. In any case you can have factory like shared_factory extension and build you decorator there manually.

**Comment by ColinDuquesnoy** [comment]
Thank you. A factory like shared_factory was exactly what I needed.
