### ISSUE TITLE
Impossible to create shared_ptr on class with Private copy or move constructor 

### ISSUE THREAD

**Issue by AxelVE** [boost-ext/di#270]
I use this simple example to present my problem. In my original issue I can't use a copy or a move constructor due to limitation of external heritage where those constructors are private.

This is the only reason why I need to use a shared_ptr... but it doesn't work needer with pointer.

```
#include <memory>
#include <boost/di.hpp>
namespace di = boost::di;

class S{};

class C
{
public:
	virtual ~C(){};
	C(){};
	virtual bool Done() const = 0;
private: /*Remove it to control*/
	C(C &&) {};
	C(const C &) {};
};

class Cc : public C
{
public:
	Cc(S* const s) :
		m_s{s} {}

	virtual bool Done() const
	{	return false; 	}
private: /*Remove it to control*/
	Cc(Cc &&c) : 
		C(std::move(c))
	{ 	m_s = std::move(c.m_s); }
	Cc(const Cc &c) : C(c)
	{	m_s = c.m_s; }

private:
	S* m_s;
};

int main()
{
	S* const s = new S();
	auto injector = di::make_injector(
		di::bind<C>().to<Cc>(),
		di::bind<S>().to(s)
	  );
	return injector.create<std::shared_ptr<C>>()->Done() == true;
}
```

I think the object should be created accordingly to his final format before being moved... or I'm doing something wrong !

Thanks the consideration and your amazing work !

**Comment by kanstantsin-chernik** [comment]
@AxelVE sorry but I don't understand what are your expectations here. I can try to help but I need clear example with `assert`.

**Comment by AxelVE** [comment]
The injector won't allow this code to compile unless the first "private :" in each class are removed. 

> error: could not convert ‘((boost::di::v1_0_1::core::successful::wrapper<Cc, boost::di::v1_0_1::wrappers::unique<boost::di::v1_0_1::scopes::unique, Cc*> >*)this)->boost::di::v1_0_1::core::successful::wrapper<Cc, boost::di::v1_0_1::wrappers::unique<boost::di::v1_0_1::scopes::unique, Cc*> >::wrapper_’ from ‘boost::di::v1_0_1::wrappers::unique<boost::di::v1_0_1::scopes::unique, Cc*>’ to ‘Cc’`

But in my real case the class C comes from an external library and if I force the copy it create bugs in the library.

**Comment by kanstantsin-chernik** [comment]
It seems you are trying to use private constructor of C from private constructor CC. It is not suppose to work even without injector. Try to use CC(CC&&) = delete;

**Comment by AxelVE** [comment]
Yes, you are correct about using `CC(CC&&) = delete; `
Once I use it I still have my original problem !

This works fine :
```
class S{};

class C
{
public:
	virtual ~C(){};
	C(){};
	virtual bool Done() const = 0;
private:
	C(C &&) {};
	C(const C &) {};
};

class Cc : public C
{
public:
	Cc(S* const s) :
		m_s{s} {}

	virtual bool Done() const
	{	return false; 	}

private:
	Cc(Cc &&c) = delete;
	Cc(const Cc &c)  = delete;

private:
	S* m_s;
};

int main()
{
	S* const s = new S();
	std::shared_ptr<C> c = std::make_shared<Cc>(s);
	return c->Done() == true;
}
```

And I get a compilation error with this version of the main:
```
int main()
{
	S* const s = new S();
	auto injector = di::make_injector(
		di::bind<C>().to<Cc>(),
		di::bind<S>().to(s)
	  );
	return injector.create<std::shared_ptr<C>>()->Done() == true;
}
```

**Comment by kanstantsin-chernik** [comment]
@AxelVE What compiler are you using? Your example successfully compiled under msvc and gcc.

**Comment by AxelVE** [comment]
OK ! Base on your last remark I run several tests : all wrong. Then I reinstall the di.hpp library and everything went fine. 
Afterwards I can't see where come from this error with the hpp file.

Sorry for the trouble and thanks for your help !
