### ISSUE TITLE
Can one class have only 10 dependencies at most?

### ISSUE THREAD

**Issue by sinall** [boost-ext/di#271]
It is very possible that a class can have more than 10 dependencies in a complex application.
Any workaround?

============================================================

If I define BOOST_DI_CFG_CTOR_LIMIT_SIZE like:

```
#define BOOST_DI_CFG_CTOR_LIMIT_SIZE 11
#include <boost/di.hpp>

```

Environment:
* Windows 10
* Visual Studio 2015U3

There are more errors:

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	C2955	'boost::di::v1_0_2::aux::is_convertible': use of class template requires template argument list	ShiPanE_App	  \di-1.1.0\include\boost\di.hpp	2617	
> Error	C4996	'boost::di::v1_0_2::core::injector<TConfig,boost::di::v1_0_2::core::pool<boost::di::v1_0_2::aux::type_list<>>,boost::di::v1_0_2::core::dependency<TScope,T,TExpected,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,DbSessionWrapper,DbSessionWrapper,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,DbMigrationService,DbMigrationService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,InfraApiHelper,InfraApiHelper,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,ServiceManager,ServiceManager,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,TcAutoLoginTask,TcAutoLoginTask,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::injector<TConfig,boost::di::v1_0_2::core::pool<boost::di::v1_0_2::aux::type_list<>>,boost::di::v1_0_2::core::dependency<TScope,AutoUpdateService,AutoUpdateService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,BrokerService,BrokerService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,ConfigService,ConfigService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,HttpService,HttpService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,MessageService,MessageService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,OcrService,OcrService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,PortfolioService,PortfolioService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,PortfolioSnapshotService,PortfolioSnapshotService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,ProductUsageService,ProductUsageService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,QuoteService,QuoteService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,ReportColumnMappingService,ReportColumnMappingService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,ReportFilterService,ReportFilterService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,StompService,StompService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,TcAutoLoginService,TcAutoLoginService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,TcClientService,TcClientService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,TdxAutoLoginService,TdxAutoLoginService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,ThsAutoLoginService,ThsAutoLoginService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,UiService,UiService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,UserService,UserService,boost::di::v1_0_2::no_name,void>>,boost::di::v1_0_2::core::injector<TConfig,boost::di::v1_0_2::core::pool<boost::di::v1_0_2::aux::type_list<>>,boost::di::v1_0_2::core::dependency<TScope,CShiPanE_AppDlgFactory,CShiPanE_AppDlgFactory,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,CLoginDialogFactory,CLoginDialogFactory,boost::di::v1_0_2::no_name,void>>>::create': creatable constraint not satisfied	ShiPanE_App	c:\project\bootstrapper.cpp	91	
> Error	C4996	'boost::di::v1_0_2::core::injector<TConfig,boost::di::v1_0_2::core::pool<boost::di::v1_0_2::aux::type_list<>>,boost::di::v1_0_2::core::dependency<TScope,T,TExpected,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,DbSessionWrapper,DbSessionWrapper,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,DbMigrationService,DbMigrationService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,InfraApiHelper,InfraApiHelper,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,ServiceManager,ServiceManager,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,TcAutoLoginTask,TcAutoLoginTask,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::injector<TConfig,boost::di::v1_0_2::core::pool<boost::di::v1_0_2::aux::type_list<>>,boost::di::v1_0_2::core::dependency<TScope,AutoUpdateService,AutoUpdateService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,BrokerService,BrokerService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,ConfigService,ConfigService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,HttpService,HttpService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,MessageService,MessageService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,OcrService,OcrService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,PortfolioService,PortfolioService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,PortfolioSnapshotService,PortfolioSnapshotService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,ProductUsageService,ProductUsageService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,QuoteService,QuoteService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,ReportColumnMappingService,ReportColumnMappingService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,ReportFilterService,ReportFilterService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,StompService,StompService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,TcAutoLoginService,TcAutoLoginService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,TcClientService,TcClientService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,TdxAutoLoginService,TdxAutoLoginService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,ThsAutoLoginService,ThsAutoLoginService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,UiService,UiService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,UserService,UserService,boost::di::v1_0_2::no_name,void>>,boost::di::v1_0_2::core::injector<TConfig,boost::di::v1_0_2::core::pool<boost::di::v1_0_2::aux::type_list<>>,boost::di::v1_0_2::core::dependency<TScope,CShiPanE_AppDlgFactory,CShiPanE_AppDlgFactory,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,CLoginDialogFactory,CLoginDialogFactory,boost::di::v1_0_2::no_name,void>>>::create': creatable constraint not satisfied	ShiPanE_App	c:\project\bootstrapper.cpp	92	
> Error	C4996	'boost::di::v1_0_2::core::injector<TConfig,boost::di::v1_0_2::core::pool<boost::di::v1_0_2::aux::type_list<>>,boost::di::v1_0_2::core::dependency<TScope,T,TExpected,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,DbSessionWrapper,DbSessionWrapper,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,DbMigrationService,DbMigrationService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,InfraApiHelper,InfraApiHelper,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,ServiceManager,ServiceManager,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,TcAutoLoginTask,TcAutoLoginTask,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::injector<TConfig,boost::di::v1_0_2::core::pool<boost::di::v1_0_2::aux::type_list<>>,boost::di::v1_0_2::core::dependency<TScope,AutoUpdateService,AutoUpdateService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,BrokerService,BrokerService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,ConfigService,ConfigService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,HttpService,HttpService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,MessageService,MessageService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,OcrService,OcrService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,PortfolioService,PortfolioService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,PortfolioSnapshotService,PortfolioSnapshotService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,ProductUsageService,ProductUsageService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,QuoteService,QuoteService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,ReportColumnMappingService,ReportColumnMappingService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,ReportFilterService,ReportFilterService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,StompService,StompService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,TcAutoLoginService,TcAutoLoginService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,TcClientService,TcClientService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,TdxAutoLoginService,TdxAutoLoginService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,ThsAutoLoginService,ThsAutoLoginService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,UiService,UiService,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,UserService,UserService,boost::di::v1_0_2::no_name,void>>,boost::di::v1_0_2::core::injector<TConfig,boost::di::v1_0_2::core::pool<boost::di::v1_0_2::aux::type_list<>>,boost::di::v1_0_2::core::dependency<TScope,CShiPanE_AppDlgFactory,CShiPanE_AppDlgFactory,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,CLoginDialogFactory,CLoginDialogFactory,boost::di::v1_0_2::no_name,void>>>::create': creatable constraint not satisfied	ShiPanE_App	c:\project\bootstrapper.cpp	93	
> Error	C2955	'boost::di::v1_0_2::type_traits::ctor': use of class template requires template argument list	ShiPanE_App	  \di-1.1.0\include\boost\di.hpp	925	
> Error	C2938	'ctor_impl_t<boost::di::v1_0_2::aux::is_constructible,CLoginDialogFactory>' : Failed to specialize alias template	ShiPanE_App	  \di-1.1.0\include\boost\di.hpp	925	
> Error	C2938	'ctor_impl_t<boost::di::v1_0_2::aux::is_constructible,CShiPanE_AppDlgFactory>' : Failed to specialize alias template	ShiPanE_App	  \di-1.1.0\include\boost\di.hpp	925	
> Error	C2938	'ctor_impl_t<boost::di::v1_0_2::aux::is_constructible,ServiceManager>' : Failed to specialize alias template	ShiPanE_App	  \di-1.1.0\include\boost\di.hpp	925	
> Error	C2510	'second': left of '::' must be a class/struct/union	ShiPanE_App	  \di-1.1.0\include\boost\di.hpp	2613	
> Error	C2039	'type': is not a member of 'boost::di::v1_0_2::ctor_traits<T,int>'	ShiPanE_App	  \di-1.1.0\include\boost\di.hpp	922	
> Error	C2039	'type': is not a member of 'boost::di::v1_0_2::ctor_traits<T,int>'	ShiPanE_App	  \di-1.1.0\include\boost\di.hpp	922	
> Error	C2039	'type': is not a member of 'boost::di::v1_0_2::ctor_traits<T,int>'	ShiPanE_App	  \di-1.1.0\include\boost\di.hpp	922	
> Error	C2794	'type': is not a member of any direct or indirect base class of 'boost::di::v1_0_2::type_traits::ctor_impl<boost::di::v1_0_2::aux::is_constructible,T,int,int>'	ShiPanE_App	  \di-1.1.0\include\boost\di.hpp	925	
> Error	C2794	'type': is not a member of any direct or indirect base class of 'boost::di::v1_0_2::type_traits::ctor_impl<boost::di::v1_0_2::aux::is_constructible,T,int,int>'	ShiPanE_App	  \di-1.1.0\include\boost\di.hpp	925	
> Error	C2794	'type': is not a member of any direct or indirect base class of 'boost::di::v1_0_2::type_traits::ctor_impl<boost::di::v1_0_2::aux::is_constructible,T,int,int>'	ShiPanE_App	  \di-1.1.0\include\boost\di.hpp	925	
> Error	C3203	'type': unspecialized class template can't be used as a template argument for template parameter '<unnamed-symbol>', expected a real type	ShiPanE_App	  \di-1.1.0\include\boost\di.hpp	903	
> Error	C3203	'type': unspecialized class template can't be used as a template argument for template parameter 'T2', expected a real type	ShiPanE_App	  \di-1.1.0\include\boost\di.hpp	922	
> Error	C2385	ambiguous access of 'second'	ShiPanE_App	  \di-1.1.0\include\boost\di.hpp	2613	
>

**Comment by kris-jusiak** [comment]
Hey @sinall,

Yeah,  BOOST_DI_CFG_CTOR_LIMIT_SIZE has to be <= 10 (http://boost-experimental.github.io/di/overview/index.html) to be cross platform.

From implementation point of view it could be any number but in MSVC is set to 10 due to missing index_sequence detection and to be consistent with BOOST_DI_INJECT.

You can use di::inject to specify any number of ctor parameters -> http://boost-experimental.github.io/di/user_guide/index.html#di_inject

The other wknd you can do is to set
```cpp
#define __has_builtin(...) 1
```

before including boost/di.hpp

This way an __make_integer_seq intrinsic will be taken and the limitation shouldn't occur.

**Comment by sinall** [comment]
@krzysztof-jusiak 

Both of 2 solutions don't work. Here's an example:


```
// ConsoleApplication2.cpp : Defines the entry point for the console application.
//

#include "stdafx.h"

#define __has_builtin(...) 1
#include "di.hpp"

#include <memory>

namespace di = boost::di;

struct C1 {
};

struct C2 {
};

struct C3 {
};

struct C4 {
};

struct C5 {
};

struct C6 {
};

struct C7 {
};

struct C8 {
};

struct C9 {
};

struct C10 {
};

struct C11 {
};

struct App {
public:
	App(C1& c1, C2& c2, C3& c3, C4& c4, C5& c5, C6& c6, C7& c7, C8& c8, C9& c9, C10& c10, C11& c11) {
	}
};

int main()
{
	const auto injector = di::make_injector(
		di::bind<C1>().to<C1>(),
		di::bind<C2>().to<C2>(),
		di::bind<C3>().to<C3>(),
		di::bind<C4>().to<C4>(),
		di::bind<C5>().to<C5>(),
		di::bind<C6>().to<C6>(),
		di::bind<C7>().to<C7>(),
		di::bind<C8>().to<C8>(),
		di::bind<C9>().to<C9>(),
		di::bind<C10>().to<C10>(),
		di::bind<C11>().to<C11>()
	);
	injector.create<App>();

	return 0;
}

```

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	C4996	'boost::di::v1_0_2::core::injector<TConfig,boost::di::v1_0_2::core::pool<boost::di::v1_0_2::aux::type_list<>>,boost::di::v1_0_2::core::dependency<TScope,T,TExpected,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,C2,C2,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,C3,C3,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,C4,C4,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,C5,C5,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,C6,C6,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,C7,C7,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,C8,C8,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,C9,C9,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,C10,C10,boost::di::v1_0_2::no_name,void>,boost::di::v1_0_2::core::dependency<TScope,C11,C11,boost::di::v1_0_2::no_name,void>>::create': creatable constraint not satisfied	ConsoleApplication2	c:\users\ruigao\documents\visual_studio_2015\projects\consoleapplication2\consoleapplication2\consoleapplication2.cpp	68	
> Error (active)		expected an expression	ConsoleApplication2	c:\ConsoleApplication2.cpp	68	
> Warning	C4506	no definition for inline function 'App *boost::di::v1_0_2::concepts::type<T>::has_to_many_constructor_parameters::max<10>::error(boost::di::v1_0_2::_)'	ConsoleApplication2	c:\users\ruigao\documents\visual_studio_2015\projects\consoleapplication2\consoleapplication2\consoleapplication2.cpp	72	
> Error (active)		no instance of function template "boost::di::v1_0_2::make_injector" matches the argument list	ConsoleApplication2	c:\ConsoleApplication2.cpp	55	
> Error (active)		type name is not allowed	ConsoleApplication2	c:\ConsoleApplication2.cpp	68
