### ISSUE TITLE
Static context ?

### ISSUE THREAD

**Issue by dimarusyy** [boost-ext/di#274]
Please, feel free to close the case if my assumption is wrong.

I noticed that my shared_ptr<> objects created with di::injector::create() are being deleted after main() exits. Does it happen because of injector keeping reference to shared_ptr<> in static objects?
If so, would it be helpful to add cleanup() method to di::injector() that will release all objects it keeps ?

**Comment by kanstantsin-chernik** [comment]
You are right. At the moment singleton is static variable. In the next version we are going to introduce shared_ptr as default singleton scope. If you don't like it use shared scope extension.
