### ISSUE TITLE
Impossible to conditionally use different injectors

### ISSUE THREAD

**Issue by ranrav** [boost-ext/di#286]
It would be very useful to be able to have multiple function that can build injectors for different scenarios, and then somewhere have a condition to call the wanted one.

The problem is that since boost::di::make_injector returns a nested struct i, every call to make_injector returns a value of a different type.

So code like this won't compile since the types are not compatible:
     auto myInjector = condition ? makeInjector1() : makeInjector2();

Similarly, calls to make_injector must assign the returned value to an auto variable, so it's impossible
for example to store the injector in a class member if I want to have some class wrap the functionality of initializing modules and injecting dependencies.

It seems like the only way to use an injector is in a local variable in a function, or a global variable (since they have to be defined as auto) which is very limiting.

The only alternative I see is for using auto is to use injector<T> for some specific type T, but then this injector is limited to only creating a T, and it will fail to inject any other dependencies in it. This is shown in the modules examples, but in that example it's impossible for module 1 to bind a dependency that is needed by something in module 2. Only the top level types are creatable.

What I'm asking is, would it be feasible to have some non generic type like boost::di::injector, which all injectors would be castable to, so that there would be more flexibility in working with different injectors?

**Comment by kris-jusiak** [comment]
Thanks, @ranrav. It's possible with the type-erased injector (di::injector<Ts...>).
You can also take a look into dynamic bindings - > http://boost-experimental.github.io/di/examples/index.html#dynamic-bindings, which reverse your intial problem but allows to solve it too.

Your example
```cpp
auto myInjector = condition ? makeInjector1() : makeInjector2();
```

might be found below

```cpp
#include <boost/di.hpp>
#include <cassert>
#include <memory>

namespace di = boost::di;

struct interface {
  virtual ~interface() = default;
  virtual void foo() = 0;
};

struct implementation1 : interface {
  void foo() override {}
};

struct implementation2 : interface {
  void foo() override {}
};

int main() {
  auto value = true;

  {
    const auto injector =
        value ? di::injector<std::shared_ptr<interface>>{di::make_injector(di::bind<interface>.to<implementation1>())}
              : di::injector<std::shared_ptr<interface>>{di::make_injector(di::bind<interface>.to<implementation2>())};
    assert(dynamic_cast<implementation1*>(injector.create<std::shared_ptr<interface>>().get()));
  }

  value = false;
  {
    const auto injector =
        value ? di::injector<std::shared_ptr<interface>>{di::make_injector(di::bind<interface>.to<implementation1>())}
              : di::injector<std::shared_ptr<interface>>{di::make_injector(di::bind<interface>.to<implementation2>())};
    assert(dynamic_cast<implementation2*>(injector.create<std::shared_ptr<interface>>().get()));
  }
}
```

**Comment by ranrav** [comment]
Thanks for replying, @krzysztof-jusiak.

But I think using a specific `di::injector<T>` is not viable for complex scenarios because it would only allow creating a `T`. 

My goal is to be able to build multiple modules, where boost::di would be used as the way to hide each module's implementation details. 
Each module exposes only interface definitions, and a single public function that returns an injector that can inject all the classes this module wants to provide, without exposing actual implementation details.

The challenge is that the injector that a module provides should be able to create all the interfaces that this module has bound in its injector.

For example:
Module 1 creates an injector binding IA to A and IB to B.
Module 2 creates an injector binding IC to C and ID to D.
The class D from module 2 depends on IA and IB.

If the functions creating the injectors return `auto`, then this works:
```cxx
auto inj = di::make_injector(make_module1_injector(), make_module2_injector());
auto d = inj.create<std::shared_ptr<ID>>();
```

But now I don't have a type `T` to be used in the `di::injector<T>` that each module would return.
If the function in module 1 returns a `di::injector<IA>`, the code above would fail because the dependency `IB` of `D` is not available, and vice versa.

Would it be feasible to have a type which all the injectors from all the modules would be castable to, but which would not be limited to creating only 1 specific type?

Thanks
