### ISSUE TITLE
no instance of function template "boost::di::v1_0_2::make_injector" matches the argument list

### ISSUE THREAD

**Issue by nicholasc** [boost-ext/di#302]
## Expected Behavior
Using the basic example from the readme, I would expect the following code to compile:
```c++
const auto injector = di::make_injector(
  di::bind<int>.to(42),
  di::bind<double>.to(87.0)
);
```

## Actual Behavior
I get a compile error
```
no instance of function template "boost::di::v1_0_2::make_injector" matches the argument list
71		            argument types are: (dependency, dependency)
```

## Steps to Reproduce the Problem

  1.  Use the Quick guide - Create object graph example in the readme

## Specifications

  - Version: 1.0.2
  - Platform: Windows 10
  - Subsystem: Microsoft Visual Studio Community 2017 Version 15.5.2

I know this is a long shot. Let me know if I need to provide additional information.

**Comment by kris-jusiak** [comment]
Thanks, @nicholasc.

I think MSVC still doesn't support DI variable template usage. Hence, you have to put `()` after bind.

```cpp
di::bind<int>().to(42)
di::bind<double>().to(87.0)
```

Working example here -> https://godbolt.org/g/vBp3hD

Hopefully, that will help.

**Comment by nicholasc** [comment]
Well that was simple... Thanks @krzysztof-jusiak.

Should this be documented in the readme or somewhere else?

**Comment by garyng** [comment]
Same environment as OP, the code still compiles, but it still shows up as errors. Any ideas?

![image](https://user-images.githubusercontent.com/4453664/44008559-9c52a4ac-9ed7-11e8-8aa7-2e098cbfee61.png)
