### ISSUE TITLE
[Question] Typo in top-level README?

### ISSUE THREAD

**Issue by JoeLoser** [boost-ext/di#304]
## Expected Behavior
In the section `Quick guide - Bind concepts` I expect the struct identifier `Stremable` to actually be `Streamable`. 

## Actual Behavior
There is inconsistency. Later parts of the example code refer to both `Stremable` and `Streamable`.

**Comment by kris-jusiak** [comment]
Thanks, @JoeLoser. Fixed by https://github.com/boost-experimental/di/pull/307.
