### ISSUE TITLE
configurable default scope

### ISSUE THREAD

**Issue by tobiaslieber** [boost-ext/di#309]
Can we make the default scope, which is currently deduce, configurable in the config? For example if we would like to use the the scoped scope or session scope as default.

Not sure if this actually requires changes in the DI or if it is possible to implement as an extension. But after some research I think it is quiet hard or even impossible to implement as an extension.

**Comment by kanstantsin-chernik** [comment]
Hey, The good news is yes!
Few weeks ago Kris introduced this feature.

You can have a look at `di::extension::shared_config` to understand how to override default deduced scopes and `https://github.com/boost-experimental/di/blob/cpp14/extension/test/scopes/shared.cpp` to  see how to use the config with overrode scopes
