### ISSUE TITLE
Const reference to object in 'unique' scope cannot be created

### ISSUE THREAD

**Issue by kanstantsin-chernik** [boost-ext/di#313]
## Expected Behavior
`injector.create<const per_request&>();` should return const reference temporary object

## Actual Behavior
`1>C:\Projects\di\example\scopes.cpp(28): warning C4996: 'boost::di::v1_1_0::core::injector<TConfig,boost::di::v1_1_0::core::pool<boost::di::v1_1_0::aux::type_list<>>,boost::di::v1_1_0::core::dependency<T,TExpected,TGiven,TName,TPriority>>::create': creatable constraint not satisfied`

## Steps to Reproduce the Problem

```
struct per_request {
  virtual ~per_request() noexcept = default;
  virtual void dummy() = 0;
};
struct per_request_impl : per_request {
  void dummy() override {}
};

int main() {
  auto injector = di::make_injector(
    di::bind<per_request>().to<per_request_impl>().in(di::unique)
  );
  injector.create<const per_request&>();
}

```

## Specifications

  - Version: Latest
  - Platform: MSVC

**Comment by kris-jusiak** [comment]
Well, the unique scope is not convertible to const& as the reference would point to a dead object. Not sure, why we would like to return a reference to a temporary?

**Comment by kanstantsin-chernik** [comment]
@krzysztof-jusiak oh, you are right.

The problem I am trying to solve is to create all objects in instance scope one by one for test purpose using modified `eager_singletons` example (just to make sure that no one throw an exception during construction/destruction). Unfortunately, there is no way to cover all binding type cases. `shared_ptr` and `const &` cover the majority but still there are exceptions. Do you have any ideas how can I do it?

```
	template <class TDependency, class TInjector, class TScope,
		std::enable_if_t<std::is_same<typename TDependency::scope, TScope>::value, int> = 0>
	void create_scope_eagerly_impl(const boost::di::aux::type<TDependency>&, const TInjector& injector, const TScope&) {
		injector.template create<const typename TDependency::expected&>();
	}

	template <class TDependency, class TInjector, class TScope,
		std::enable_if_t<!std::is_same<typename TDependency::scope, TScope>::value, int> = 0>
	void create_scope_eagerly_impl(const boost::di::aux::type<TDependency>&, const TInjector&, const TScope&) {}

	template <class... TDeps, class TInjector, class TScope>
	void create_scope_eagerly(const boost::di::aux::type_list<TDeps...>&, const TInjector& injector, const TScope& scope) {
		[](...) {}((create_scope_eagerly_impl(boost::di::aux::type<TDeps>{}, injector, scope), 0)...);
	}

	template <class TInjector>
	void test_instances(const TInjector& injector)
	{
		namespace di = boost::di;
		using namespace di::extension;
		create_scope_eagerly(typename TInjector::deps{}, injector, di::scopes::instance{});
	}
```
