### ISSUE TITLE
Serialize example is not compiling with -std=c++17 flag turned on

### ISSUE THREAD

**Issue by melg8** [boost-ext/di#329]
I've tried to compile [serialization](http://boost-experimental.github.io/di/extensions/index.html#serialize) example with clang 6.0 / gcc 7.3 with enabled -std=c++17 flag.

## Expected Behavior
Should compile just fine as with -std=c++14 flag.

## Actual Behavior
Fails to compile on clang 6.0 (with flag -std=c++17) with errors (example one of them):
```
<source>:88:32: error: implicit instantiation of undefined template 'boost::di::v1_1_0::core::array<boost::di::v1_1_0::extension::archive>'

            const auto align = alignof(given);
```

Fails to compile on gcc 7.3 (with flag -std=c++17) with errors (example one of them):
```
<source>:88:24: error: invalid application of '__alignof__' to incomplete type 'given {aka boost::di::v1_1_0::core::array<boost::di::v1_1_0::extension::archive>}'
```
## Steps to Reproduce the Problem

  1. Take serialize code snippet and compile it with -std=c++14 as shown in online [example](https://gcc.godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAKxAEZSAbAQwDtRkBSAJgCFufSAZ1QBXYskwgA5BwAMAQW4BmLADM8LTAGoeAeV0BlACoB9ACIBJcxYPyeAGWwmDACXkAlbGZMAFI%2B/MvAFUAYSMLXQA5OUUuJQ1kBhEsLQ4lEIQCAgAHQRAAenziJgB3ADpgQgQRACMRQUxxVBYCTBaytABbfJrUVEECAFpMAA9sxrxOtoImBnz8fORs7NoAFnyEpKwevoH5vDKEZbTsGLO4zeTtNJDZ4BIqzpPz%2BJZEq9T01RE3gjxm2bPBTKS4pG6CAbETBMJ5KU7Ai5vLbXdKQjTAIGxV7vMHpABumGQRGImJiekMpksJki8gAstgDD55CEnDxsABxCzRBQsGGYQTZJgSLSjVosQT/FipADsfGBClanWyzFanxCiSYEK0RkxTBERC0wEwBBMBAAnuMIABKGVy%2BRaLQDdAgEBothaKGCEQMAhpO0g1RaNQaTDoCAmWkGEImABq2HcVpiDr1BvN40%2BZkdBGdroIxHRHFl3AAbCYTAAxIKREIGCzssscACsPC4XCbZkLHaUdodaHFBC0KdQWjwGa0acwTZ4snbGbSmbAUi0i8%2B5a0tC0IC0M%2B7SY9/O9A/n44tmDKXpqkIgeFIJ/GZQYbWABAQ1q0gy00vfI8Tu4RSkwBg8EDYNNDDMsNTYMtEwUZN9WHCcxydF03QxIsuFLXxPCMIwAE0KyrMIIkiBtmy4Wh207P0909Q8xwnc9aivWRbwYx82BfN8P1oX9/TiQDgKDTB1DA8MTHZEJoxMGD7UHeC7xRTNkNzfM2ELPgMLLHxsLwgjq3CKJSJbYtKOlLse33L0fXo09GMvPMIBYhSHyfTibW43iXkAhovOIYgSFSVsfBVVQSE6LQWFQAcvWWEhWnQMAwG4Nt/zafBVD3ZSoWVIVMAgWifTKGpMEqFhrVvAqCDKNLyuXJdF1vRcTEXTzYP3AgxClSrqOBMyzgUSERCJQdxAQPACVtTLsxQvN0S0QUXx62TlO%2BX5JRuZAECYYgACprROea8yWh1lNQhTjpHFotFQVRVAaX0/0UPrHsG4a%2B1aEYBy3ZSCSJEgbm2zbxsnOFJrajQBxuu7jTHHd/Weu1XuiiZZjwAAvJgakfTcsxzX7iQB0bgYO9SqMemIkfm1AgOQM0TGAERtvQMHZOyam8Fp%2BnGeIMMbXUrRNsJABrN9jzzEQQZ4GUOzagA/NmabphmmdF2UBYQYXRaUTNVFmHzu2lqamD%2BZAtF6amS3VzW%2BaLNqTpmE25INZWebHXWGH1iyHShDriClF30AuqjevM/r5EVHLVQ25gtSMdlgZYW8NVjiwWCoQkCbhCnppAVaiXW9JNu2vbf2wQ1jRMbIHL7AZtVT9O/pJDDbxWvXMFNU8bYsn3OsmhGzj6%2BVw8wJUVRRdUY8EbV44JROBcnuu04z/6s4GnO87%2BZoNq23b9tBo0TSr4gIBrgdwiXxvLY0BviRbnPxfbicu5o41e6nEtr%2BXklG0zUm7apxWXMmZaBMBdb2r8/b7gho0bIPsTDIE1A9dUO8donAgB/C%2BxIygRzHgLKExsQZhBnm0EsaCrStVkmTeGMtFAKGTlPBo%2BZUYYyxu3BWHMzQ42yLUGmAtmjqGACzeaPCOYgD3Dgghap6GLxviveEy0HYcydsOdhyA8D8ggOfWRu1LraJtJFUYEgq5CIdO1XunQmBCzYezNRGj34YXbBAIcCln7/wdIJCAqilbcxzILZAItyFmL9mA0xXigGu1AY9Uxpj6hzSMGOLAiQJwQCfiEh0sT3SVFnmOPUIwXSJKYHTJBE5eRTCEkk08KTO4ugnM8KJ0TlGkIwloPEY5P6N0GCcCRqpkD4NaBtZoH1fQOLhHvL2pjnFHzHAfSuR10hZJIaMna7Tb64xdHgQQJgoSqEaG0CQNwSl8m1DU08zwixmQoQ0kcgYIDKQ2ZXDABzTylO0EYE54wTgujxLMCWgUTLNLeSAbahAzRfJ%2BZgVxskrlTOPHiIqQoAllCPmkw2Q8rmnVmu6QCI9pgoo8YlOFI8q5mmtJCq5DpsVTCurC%2BF/jrRIuNggQKUtkqdKzq2FF7iblwpqAi%2BlR8yXkrgkQS2jC8DMMUror%2BbLsDdO0L06E/TUQoyAiwx8pDRmXKFdcrQEBEqAuBeaMFSQIUmO1Xw/syjBxAWAFKY8qNbU3WgAnLV5q4VQ3umOKA7rbqev4NavAtrvw8S0PkANtqbQ7XDSwTlDSxUSqRfUBAJheV0vUjyvlVoGUvlvBmulWaj63hmbU%2BZCcyG5rKB640nZXXap9dDI8vBjwSjRpgJ1CyWC1qucHKFDSe1CrhWzbIKbM2xo8YSpU5pSVmvJfWv12s%2B6hzcaY/tfbB60N7cK4cjcTAtslQa/MRqQDfJNSikoY1sYn2JLu9GmBBiDEFVcwdSaR1ptlJS6YzLy4mhLSEDt5bDpkEXbeGcFyUWrodDWoO66qFhzlVIyeZQkPakEJiSm8bVWY0fPA2YDATHwejpqKeWiv5JwXkYbAYwSSrwUcbJReJUB4GZkwZYDASWnxkV/K%2BmCSC3go1RkUVHH1aFCsQXVQ4mnFmujjFZJBsFEtwQqgh4IVXoyw5OEZ2Bp1/03YOVjdNJjKggKgW8oxYG3lye89uQEBg3CMIIJDZQzl8DA/UyD673M0PEQpyRhHY6UfM/PIj2oyNEcc1oIIqGaP2zo6bBjTG9PKgM6PE%2BzRa6AzGgSS2JntQBbE2ZoDlmQAThMDZpBRhbyRccycYTHji2nPSDqTVc4F2oGwZ3GdFKqPGb46TVz4zOwig9tcW2umWNJZMIZhgPXBOBaKyVsrNwqtIec1BtzqLKEwbagRwu5G8uYhi47eLzH9OTZSxxjLxNm65aoxZkQeTiunlKxspBNXF0DyXRuwoQW2CDFExYyGt0YgZMERhtTrCcMMAYKaJCqm1XtwQVDm4e4fgSltaGdW20Yi3lR4GsCjoEBxWx1oXH6PmYQ2J6T/HDBmgYgUDj8UeOMc0/dCzun8gW5M%2BZkXEk9OCdE75xTvnbPids60CLvnPPieqBp8bYn6BRCsNF7ToMiv1V8/NgwM4WdHrfcgsAP7YVjbXRjUPZxYPW1jnfj/VLlqJPNNk4V%2BCoq8yCot%2BpyH0OCAunG2x68PGgP2JMjbi7zvmk5ecQQYTkI1Q3GutmplyP0iBS4Cn2Pye2uISTyENPyV0857a1Wo86Q495%2BSnubtJfk/KSILuzFwAIA7ShNA4gsCK4INs%2BkRJPpKlR9QaMtrR9Ra8Hj0XwJ2e1kgDSlr%2Bpa3qFLRiM4rAFvJXW7MLb9LYepOO7uyK5pkI3dw494jr3Pv9P%2B%2B0beIPjjQ976kxH%2BSUeZ0YtUoIoCmhbwLQQKxBr4zu/JKfxPV%2BWPD60%2B2iWcSL1hgX3/lE11Rfzmnf0lknwPkQNuTzFvEQN4mE3thzBe1f0hGhHCg2VQ1lEQNg2XWIM%2BFOFBi/yoIOizx1zLkgLqTLiAMlgr1MQ8QYK7EzEzw6x0yFSb0wBbzbxNA7yQX/17ytH7y00Hwcj5hHzHzHDYNjRqHwSFnAw8xXS0Lnw%2B2gKekzFDTDVFDaAlC3gUHJGMGsGpDpAZCZBZBMGwEiC8yHjDhBCRA%2BA2iI0aAenkXcJxHHn%2BAIJhFJB5D5AFFyiDFHGPHNgGHyTwH0MpnQGNiYBMSpwxwhhJwSPqTFxnwshl1QGNwynJn7iHkpkwFnhME6BIHbmSJmBMQVx4W0EDnqU1zNgulyJVyRxKM%2B2zmICGgHGqKhBMDqNSIEMugHGyIsjF0aNYXFxaIsgqLaCqJqJGJSKDAukEEJ2IGigX1KI3XKJGBhGVBG0WKONHjylGMtnQFvCGNqJSMtk6HQBtC3DDGeNuLDCeOfi21kmOxJ2yDqLymE3QDKBEGiIXVoCUBCRBLw2PDiDyI4JBMDGPDKCUCUGKPGSeLKHBMzFWFWBCSxIYGZmPFWC4DKDhg4KxJBOJIXUbEbHJIJOpKKnon6PYP/ipIfFhIXWLGLG6MxJBKnmPGlGlGgxcN%2BMY2Zk9GNFVj/1BJxPe3WxhKt3OTANMSROVJc1VIdCxPlNAMZIfBpN/hVP1OpI1PIN7Q5JqDNP2OiQ5Kh2tK1K0CxMFIXT1Nnx%2BIdCuOaQWL3DuLWJmEeJ9JDn0MyIsQ0BlL3D12YF%2B3%2B2Nyhj3GcUdwSQoBAAsSsUmwDxuHwBdBMMZ2aBQiPwhy8TQQ4M9JTJqA0BaJCDIWwVQAgFJJkgdC1SjNYAN1jMhlNw3QdHyH72rMLj6WuGLFkFGGOPVSHJYJ2nyATPklQBqBvjaQDw6AHJuBHIuLIWg3GW8J2Mcha14LnIzjKBBLBNrS3IIB3PnGPFnJvkPIfBPIhB8IgHJORO1kvP3KJBvNUDvMYTPNJN3OujfKqh1N4m7LDV6B%2BEDn/lPMcnJL/KvIPMJOeJCSgtkBgovNawArKA5MQvWygvdgaFgowstK/IfNkAIuvLtIYGIu3NIrQr3PIoFK1R7UjN7JuBEABMkRb15DwyuMYMnL3DgvfLYsBLGT3HGOTHvO3MhLIoPKPLwCorPLiGkvfJhPksfLROfJ4P/OvKRNUrxKUsApBLkqQokp/LJJopfPQvooNNUrpNQosrovgqZOws3JMpSVZP0swqZJqFUp5I8ootUuFL8oYtFLDm7JYuVSYVVW0E4tmCDHWNTA1izHwVhGoOwD4rangLYGCPCkhAumzKn0%2BlMMlALMitvQv1IySooWYuzylMmJaEaC4rioDN4qnLagEqqlqpErRVDXCpCGXzh20FUH8nChfG0GyonNatknytzLMJYHyX5AGvKsbjvmIEYtG3ANcqktoq0pkrlNUsUu2vapvMouMu/LUvRI8p0tOofL0sOsIsMt0rMqCusuuu3NsvMs0qOqwtUofmepBO8terPN8ruqsphJOpwtcsCpBscvPDWq83XSkCtEYGkEbCkFIDmqkFkDRtQGkGrKbRH2EDEGFGUFoDRu90xsRqRqFhACUGLDKEbCHMbDiHInImlAAE5iwObkapBVg0aMasbSAcapA0a8gWJyasaka4BYAkAuhsg8BHwyAKBUslR5bGgUBozgAhyWJ1AfRGg8gIAahpABaKzeRiBQUpBSbSAugqUCBdAWA2Mja0asALE2BHxHbSB8AoR84CQ8gKbSBRhCR9RJALa0boEGB3bZpOhpBSakaNaUB%2BB%2BBGA8BLx4AkbUAq5JRfbBgnR5xOB8aeA1gRbRBxBJAeJubUb0b3ahaRgAAOYsQYYsVYH7QROmlC0iiAXAQgAKEm28EIVAFWhWwKJQENPGjSHgMmx28hUgampQFC2gWQYsNYJQVYRsPEuutmmupQbm3m0gKO%2Belifm7G6QEWkAMWye0gKWxAEAUQHIfUcgSgWW1W4gOgf2/AYkF%2BkoYobIaOxG8uvmqu6QEmrQEoKoLQWu%2Buxu5urQVu8kieimqemepQVEtElB1B1B7e/%2Bv2oWk%2Bs%2B%2BB2O6QLgNGve2QA%2BgB4W0gcWym0gAkYgWakAVYIAA%3D%3D%3D) - everything compiles just fine.
  1.  change -std=c++14 to -std=c++17 flag as shown in online [example](https://gcc.godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAKxAEZSAbAQwDtRkBSAJgCFufSAZ1QBXYskwgA5BwAMAQW4BmLADM8LTAGoeAeV0BlACoB9ACIBJcxYPyeAGWwmDACXkAlbGZMAFI%2B/MvAFUAYSMLXQA5OUUuJQ1kBhEsLQ4lEIQCAgAHQRAAenziJgB3ADpgQgQRACMRQUxxVBYCTBaytABbfJrUVEECAFpMAA9sxrxOtoImBnz8fORs7NoAFnyEpKwevoH5vDKEZbTsGLO4zeTtNJDZ4BIqzpPz%2BJZEq9T01RE3gjxm2bPBTKS4pG6CAbETBMJ5KU7Ai5vLbXdKQjTAIGxV7vMHpABumGQRGImJiekMpksJki8gAstgDD55CEnDxsABxCzRBQsGGYQTZJgSLSjVosQT/FipADsfGBClanWyzFanxCiSYEK0RkxTBERC0wEwBBMBAAnuMIABKGVy%2BRaLQDdAgEBothaKGCEQMAhpO0g1RaNQaTDoCAmWkGEImABq2HcVpiDr1BvN40%2BZkdBGdroIxHRHFl3AAbCYTAAxIKREIGCzssscACsPC4XCbZkLHaUdodaHFBC0KdQWjwGa0acwTZ4snbGbSmbAUi0i8%2B5a0tC0IC0M%2B7SY9/O9A/n44tmDKXpqkIgeFIJ/GZQYbWABAQ1q0gy00vfI8Tu4RSkwBg8EDYNNDDMsNTYMtEwUZN9WHCcxydF03QxIsuFLXxPCMIwAE0KyrMIIkiBtmy4Wh207P0909Q8xwnc9aivWRbwYx82BfN8P1oX9/TiQDgKDTB1DA8MTHZEJoxMGD7UHeC7xRTNkNzfM2ELPgMLLHxsLwgjq3CKJSJbYtKOlLse33L0fXo09GMvPMIBYhSHyfTibW43iXkAhovOIYgSFSVsfBVVQSE6LQWFQAcvWWEhWnQMAwG4Nt/zafBVD3ZSoWVIVMAgWifTKGpMEqFhrVvAqCDKNLyuXJdF1vRcTEXTzYP3AgxClSrqOBMyzgUSERCJQdxAQPACVtTLsxQvN0S0QUXx62TlO%2BX5JRuZAECYYgACprROea8yWh1lNQhTjpHFotFQVRVAaX0/0UPrHsG4a%2B1aEYBy3ZSCSJEgbm2zbxsnOFJrajQBxuu7jTHHd/Weu1XuiiZZjwAAvJgakfTcsxzX7iQB0bgYO9SqMemIkfm1AgOQM0TGAERtvQMHZOyam8Fp%2BnGeIMMbXUrRNsJABrN9jzzEQQZ4GUOzagA/NmabphmmdF2UBYQYXRaUTNVFmHzu2lqamD%2BZAtF6amS3VzW%2BaLNqTpmE25INZWebHXWGH1iyHShDriClF30AuqjevM/r5EVHLVQ25gtSMdlgZYW8NVjiwWCoQkCbhCnppAVaiXW9JNu2vbf2wQ1jRMbIHL7AZtVT9O/pJDDbxWvXMFNU8bYsn3OsmhGzj6%2BVw8wJUVRRdUY8EbV44JROBcnuu04z/6s4GnO87%2BZoNq23b9tBo0TSr4gIBrgdwiXxvLY0BviRbnPxfbicu5o41e6nEtr%2BXklG0zUm7apxWXMmZaBMBdb2r8/b7gho0bIPsTDIE1A9dUO8donAgB/C%2BxIygRzHgLKExsQZhBnm0EsaCrStVkmTeGMtFAKGTlPBo%2BZUYYyxu3BWHMzQ42yLUGmAtmjqGACzeaPCOYgD3Dgghap6GLxviveEy0HYcydsOdhyA8D8ggOfWRu1LraJtJFUYEgq5CIdO1XunQmBCzYezNRGj34YXbBAIcCln7/wdIJCAqilbcxzILZAItyFmL9mA0xXigGu1AY9Uxpj6hzSMGOLAiQJwQCfiEh0sT3SVFnmOPUIwXSJKYHTJBE5eRTCEkk08KTO4ugnM8KJ0TlGkIwloPEY5P6N0GCcCRqpkD4NaBtZoH1fQOLhHvL2pjnFHzHAfSuR10hZJIaMna7Tb64xdHgQQJgoSqEaG0CQNwSl8m1DU08zwixmQoQ0kcgYIDKQ2ZXDABzTylO0EYE54wTgujxLMCWgUTLNLeSAbahAzRfJ%2BZgVxskrlTOPHiIqQoAllCPmkw2Q8rmnVmu6QCI9pgoo8YlOFI8q5mmtJCq5DpsVTCurC%2BF/jrRIuNggQKUtkqdKzq2FF7iblwpqAi%2BlR8yXkrgkQS2jC8DMMUror%2BbLsDdO0L06E/TUQoyAiwx8pDRmXKFdcrQEBEqAuBeaMFSQIUmO1Xw/syjBxAWAFKY8qNbU3WgAnLV5q4VQ3umOKA7rbqev4NavAtrvw8S0PkANtqbQ7XDSwTlDSxUSqRfUBAJheV0vUjyvlVoGUvlvBmulWaj63hmbU%2BZCcyG5rKB640nZXXap9dDI8vBjwSjRpgJ1CyWC1qucHKFDSe1CrhWzbIKbM2xo8YSpU5pSVmvJfWv12s%2B6hzcaY/tfbB60N7cK4cjcTAtslQa/MRqQDfJNSikoY1sYn2JLu9GmBBiDEFVcwdSaR1ptlJS6YzLy4mhLSEDt5bDpkEXbeGcFyUWrodDWoO66qFhzlVIyeZQkPakEJiSm8bVWY0fPA2YDATHwejpqKeWiv5JwXkYbAYwSSrwUcbJReJUB4GZkwZYDASWnxkV/K%2BmCSC3go1RkUVHH1aFCsQXVQ4mnFmujjFZJBsFEtwQqgh4IVXoyw5OEZ2Bp1/03YOVjdNJjKggKgW8oxYG3lye89uQEBg3CMIIJDZQzl8DA/UyD673M0PEQpyRhHY6UfM/PIj2oyNEcc1oIIqGaP2zo6bBjTG9PKgM6PE%2BzRa6AzGgSS2JntQBbE2ZoDlmQAThMDZpBRhbyRccycYTHji2nPSDqTVc4F2oGwZ3GdFKqPGb46TVz4zOwig9tcW2umWNJZMIZhgPXBOBaKyVsrNwqtIec1BtzqLKEwbagRwu5G8uYhi47eLzH9OTZSxxjLxNm65aoxZkQeTiunlKxspBNXF0DyXRuwoQW2CDFExYyGt0YgZMERhtTrCcMMAYKaJCqm1XtwQVDm4e4fgSltaGdW20Yi3lR4GsCjoEBxWx1oXH6PmYQ2J6T/HDBmgYgUDj8UeOMc0/dCzun8gW5M%2BZkXEk9OCdE75xTvnbPids60CLvnPPieqBp8bYn6BRCsNF7ToMiv1V8/NgwM4WdHrfcgsAP7YVjbXRjUPZxYPW1jnfj/VLlqJPNNk4V%2BCoq8yCot%2BpyH0OCAunG2x68PGgP2JMjbi7zvmk5ecQQYTkI1Q3GutmplyP0iBS4Cn2Pye2uISTyENPyV0857a1Wo86Q495%2BSnubtJfk/KSILuzFwAIA7ShNA4gsCK4INs%2BkRJPpKlR9QaMtrR9Ra8Hj0XwJ2e1kgDSlr%2Bpa3qFLRiM4rAFvJXW7MLb9LYepOO7uyK5pkI3dw494jr3Pv9P%2B%2B0beIPjjQ976kxH%2BSUeZ0YtUoIoCmhbwLQQKxBr4zu/JKfxPV%2BWPD60%2B2iWcSL1hgX3/lE11Rfzmnf0lknwPkQNuTzFvEQN4mE3thzBe1f0hGhHCg2VQ1lEQNg2XWIM%2BFOFBi/yoIOizx1zLkgLqTLiAMlgr1MQ8QYK7EzEzw6x0yFSb0wBbzbxNA7yQX/17ytH7y00Hwcj5hHzHzHDYNjRqHwSFnAw8xXS0Lnw%2B2gKekzFDTDVFDaAlC3gUHJGMGsGpDpAZCZBZBMGwEiC8yHjDhBCRA%2BA2iI0aAenkXcJxHHn%2BAIJhFJB5D5AFFyiDFHGPHNgGHyTwH0MpnQGNiYBMSpwxwhhJwSPqTFxnwshl1QGNwynJn7iHkpkwFnhME6BIHbmSJmBMQVx4W0EDnqU1zNgulyJVyRxKM%2B2zmICGgHGqKhBMDqNSIEMugHGyIsjF0aNYXFxaIsgqLaCqJqJGJSKDAukEEJ2IGigX1KI3XKJGBhGVBG0WKONHjylGMtnQFvCGNqJSMtk6HQBtC3DDGeNuLDCeOfi21kmOxJ2yDqLymE3QDKBEGiIXVoCUBCRBLw2PDiDyI4JBMDGPDKCUCUGKPGSeLKHBMzFWFWBCSxIYGZmPFWC4DKDhg4KxJBOJIXUbEbHJIJOpKKnon6PYP/ipIfFhIXWLGLG6MxJBKnmPGlGlGgxcN%2BMY2Zk9GNFVj/1BJxPe3WxhKt3OTANMSROVJc1VIdCxPlNAMZIfBpN/hVP1OpI1PIN7Q5JqDNP2OiQ5Kh2tK1K0CxMFIXT1Nnx%2BIdCuOaQWL3DuLWJmEeJ9JDn0MyIsQ0BlL3D12YF%2B3%2B2Nyhj3GcUdwSQoBAAsSsUmwDxuHwBdBMMZ2aBQiPwhy8TQQ4M9JTJqA0BaJCDIWwVQAgFJJkgdC1SjNYAN1jMhlNw3QdHyH72rMLj6WuGLFkFGGOPVSHJYJ2nyATPklQBqBvjaQDw6AHJuBHIuLIWg3GW8J2Mcha14LnIzjKBBLBNrS3IIB3PnGPFnJvkPIfBPIhB8IgHJORO1kvP3KJBvNUDvMYTPNJN3OujfKqh1N4m7LDV6B%2BEDn/lPMcnJL/KvIPMJOeJCSgtkBgovNawArKA5MQvWygvdgaFgowstK/IfNkAIuvLtIYGIu3NIrQr3PIoFK1R7UjN7JuBEABMkRb15DwyuMYMnL3DgvfLYsBLGT3HGOTHvO3MhLIoPKPLwCorPLiGkvfJhPksfLROfJ4P/OvKRNUrxKUsApBLkqQokp/LJJopfPQvooNNUrpNQosrovgqZOws3JMpSVZP0swqZJqFUp5I8ootUuFL8oYtFLDm7JYuVSYVVW0E4tmCDHWNTA1izHwVhGoOwD4rangLYGCPCkhAumzKn0%2BlMMlALMitvQv1IySooWYuzylMmJaEaC4rioDN4qnLagEqqlqpErRVDXCpCGXzh20FUH8nChfG0GyonNatknytzLMJYHyX5AGvKsbjvmIEYtG3ANcqktoq0pkrlNUsUu2vapvMouMu/LUvRI8p0tOofL0sOsIsMt0rMqCusuuu3NsvMs0qOqwtUofmepBO8terPN8ruqsphJOpwtcsCpBscvPDWq83XSkCtEYGkEbCkFIDmqkFkDRtQGkGrKbRH2EDEGFGUFoDRu90xsRqRqFhACUGLDKEbCHMbDiHInImlAAE5iwObkapBVg0aMasbSAcapA0a8gWJyasaka4BYAkAuhsg8BHwyAKBUslR5bGgUBozgAhyWJ1AfRGg8gIAahpABaKzeRiBQUpBSbSAugqUCBdAWA2Mja0asALE2BHxHbSB8AoR84CQ8gKbSBRhCR9RJALa0boEGB3bZpOhpBSakaNaUB%2BB%2BBGA8BLx4AkbUAq5JRfbBgnR5xOB8aeBaBpQRbRBxBJAeJubUb0b3ahaRgAAOYsQYYsVYH7QROmlC0iiAXAQgAKEm28EIVAFWhWwKJQENPGjSHgMmx28hUgampQFC2gWQYsNYJQVYRsPE%2Butm2upQbm3m0gKOhelifm7G6QEWkAMWqe0gKWxAEAUQHIfUcgSgWW1W4gOgf2/AYkV%2BkoYobIaOxGiuvm6u6QEmrQEoKoLQOuhupulurQNu8kyeim6e2epQVEtE1BtBtBnegBv2oW0%2B8%2BhB2O6QLgNG/e2QQ%2BwB4W0gcWym0gAkYgWakAVYIAA%3D) - observe errors.
  1. Repeat same thing with other compiler

## Specifications
  - Version: clang 6.0/gcc 7.3
  - Platform: linux

Ps. I'm very new to c++ templates dark magic, but really want to use this library for structures deserialization (for creating libfuzzer fuzz tests, with types generated from random inputs). But using c++17. So any help with hot fixes serialization example or examples of use boost di for fuzzing are appreciate.

**Comment by quixoticaxis** [comment]
"Hello world" example fails for me on clang 7 both in c++14 and c++17 mode.
