### ISSUE TITLE
How to provide unary_function when compiling DI with C++ 17

### ISSUE THREAD

**Issue by juandent** [boost-ext/di#347]
## Expected Behavior
Code should compile with C++ 17 ISO
## Actual Behavior

Because C++ 17 has removed unary_function, compilation fails.

## Steps to Reproduce the Problem

1. #include <boost/di.hpp>
2. compile with language C++ 17 ISO

##solution
Add the following code:

```
#include <functional>
template <typename ArgumentType, typename ResultType>
struct unary_function : function<ResultType(ArgumentType)>
{
	using result_type = ResultType;
	using argument_type = ArgumentType;
};
#include <boost/di.hpp>
```

## Specifications

  - Version: Visual Studio 2017 version 15.8.1
  - Platform: Windows
  - Subsystem:

**Comment by juandent** [comment]
This is a contribution not a question...

**Comment by kanstantsin-chernik** [comment]
Hey, sounds intresting.

Could you please send a PR for contribution? 

Thank you!
