### ISSUE TITLE
How to initialize (bind) member data when there are more than one members with same type?

### ISSUE THREAD

**Issue by juandent** [boost-ext/di#348]
## Expected Behavior

I thought one could set the initial value for each data member of an object created with injector.create<>, but that does not seem to be the case

## Actual Behavior
only one di::bind<int>().to(42) can be provided inside a di::make_injector call

## Steps to Reproduce the Problem

  1. Modify gui_view from the Tutorial, so it receives a third parameter in the constructor and make that a std::string.
  2. Write this code:
```
auto injector = di::make_injector(
       di::bind<iview>().to<gui_view>(),
	di::bind<int>().to(42),
	di::bind<std::string>().to("A Title"),
        di::bind<std::string>().to("Another string")); 

auto c = injector.create<app>();
```
  3. Compile the code (will get errors which disappear as soon as you remove one of the two string bindings

## conclusion

it is not possible to set the values of both std::string data members - or am I missing something?

## Specifications

  - Version: Visual Studio 2017 version 15.8.1
  - Platform: Windows
  - Subsystem:

**Comment by jferch** [comment]
@juandent have a look at [annotations](http://boost-experimental.github.io/di/tutorial/index.html#4-basic-annotations-to-the-rescue).

**Comment by kanstantsin-chernik** [comment]
@juandent It depends on how are you going to use them. It is either [annotations](http://boost-experimental.github.io/di/tutorial/index.html#4-basic-annotations-to-the-rescue) or [multiple binding](http://boost-experimental.github.io/di/examples/index.html#multiple-bindings).
