### ISSUE TITLE
circular dependencies

### ISSUE THREAD

**Issue by themagnet** [boost-ext/di#358]
I wonder how circular dependencies are handled (besides being removed from the system design)? I did not find anything about this topic in the documentation. I used version 1.0.2 in a sample project and it seems that cycles are not detected/rejected. I had the injector.create(...) hanging in _Init_thread_header on vs2017 (15.8.7). With -Zc:threadSafeInit- some object in the cycle was created with a null-dependency to another one.

**Comment by themagnet** [comment]
I guess the "lazy extension" could be a solution to this problem (with the downside of coupling the domain to this di-specific extension). Unfortunately i cannot test this because the extension folder is missing. I installed boost-di 1.0.2 via vcpkg. Do you think is worth to create an issue for vcpkg?

**Comment by kanstantsin-chernik** [comment]
The thing is: circular dependencies are code smell. DI make it harder to introduce and it is good thing.
However there is lazy extension. If you don't want to introduce dependency on di-specific code: just put extra abstraction layer there (like `IMyLazyProvider`).

**Comment by themagnet** [comment]
Thanks for your respond and the tip for the extra abstraction layer.

I copied the missing folder and the lazy extension did the job. 

I agree with circular dependencies being a code smell in general - but have not found a good solution for my problem yet: "repository" (loading entities) and using a "resolver" (loading entity references) using "repository".

If 
- hanging on resolving circular dependencies or
- creating objects will null-dependencies 

is the way *this* DI makes it harder to introduce cycles, this issue can be closed :)
