### ISSUE TITLE
How to provide default arguments to the injector?

### ISSUE THREAD

**Issue by akaegi** [boost-ext/di#360]
I really like your DI library, thanks alot!
I'm still struggling in setting it up though.
One problem I have is with registering the following type in the injector:
```
class EventAggregator : public QObject {
    Q_OBJECT
public:
    explicit EventAggregator(QObject* parent = nullptr);
```
I would expect it to call this constructor when I do `injector.create<shared_ptr<EventAggregator>>`.
However the compiler reports an error as it does not know how to resolve the `QObject* parent` dependency.

I can solve the issue by adding a second constructor to `EventAggregator` like so:
```
explicit EventAggregator(QObject* parent );
EventAggregator(...) : EventAggregator(nullptr) {}
```

However, I don't like this solution so much as it might confuse other users of the library where the `EventAggregator` resides in. 
Is there a non-intrusive solution to this problem to provide a default argument to a constructor, something like `di::ctor_traits` that let's one choose a certain constructor?

**Comment by kanstantsin-chernik** [comment]
Is it what you are looking for?
```
class EventAggregator : public QObject {
    Q_OBJECT
public:
    explicit EventAggregator(QObject* parent);
    BOOST_DI_INJECT(EventAggregator): EventAggregator(nullptr){}

```
