### ISSUE TITLE
inheritance example doesn't build

### ISSUE THREAD

**Issue by Kicer86** [boost-ext/di#369]
## Expected Behavior
As a user I want to compile and run http://boost-experimental.github.io/di/examples/index.html#inheritance example

## Actual Behavior
Example fails to build (common/config.hpp is missing)

## Steps to Reproduce the Problem

1. Enter http://boost-experimental.github.io/di/examples/index.html#inheritance
2. Click 'Run this code!'
3. build error

**Comment by kanstantsin-chernik** [comment]
@krzysztof-jusiak, it seems there is an issue with the way you push dependencies.

**Comment by kris-jusiak** [comment]
Fixed by https://github.com/boost-experimental/di/commit/cab3163b41d61442085f3f1858023201a02c9b2a
