### ISSUE TITLE
Simple facade function over di::bind compiles in clang, but does not in gcc

### ISSUE THREAD

**Issue by Warchant** [boost-ext/di#429]
## Expected Behavior

clang, apple clang and gcc should compile this code:

https://godbolt.org/z/0SQkcR

## Actual Behavior

clang compiles, gcc does not

## Steps to Reproduce the Problem

Just look at https://godbolt.org/z/0SQkcR

## Specifications

  - Version: latest
  - Platform: linux

**Comment by kris-jusiak** [comment]
Thanks, @Warchant.

GCC requires a template keyword in that context; The issue is not really related to DI.

```
template <typename... T>
auto useDerived(){
    return boost::di::bind<Base*[]>.template to<T...>();
}
```

The following work fine in both GCC and clang -> https://godbolt.org/z/WlHC3B
