### ISSUE TITLE
Although it's unique scope injector.creates a singleton

### ISSUE THREAD

**Issue by subbota-a** [boost-ext/di#432]
Consider the following example.

```
class server {};

int main()
{
	di::injector<client> injector = di::make_injector(
		di::bind<server>().in(di::unique)
	);
	std::shared_ptr<server> server1 = injector.create<std::shared_ptr<server>>();
	std::shared_ptr<server> server2 = injector.create<std::shared_ptr<server>>();
	assert(server1);
	assert(server2);
	assert(server1.get() != server2.get()); // assert failed!
}

```## Expected Behavior
I expect that if I use 'unique' I get two different servers.

**Comment by kanstantsin-chernik** [comment]
It is a bit confusing but it actually doesn't user unique scope binding in this case. If you call it with `injector.create<std::shared_ptr<server>>` it uses default shared scope.
You can try to forbid unbound instantiations and this code will fail as there is no bound shared scope.

**Comment by subbota-a** [comment]
I'm sorry but your answer isn't clear to me.
So, how to get two different 'server' instances if I want shared_ptr?

**Comment by kanstantsin-chernik** [comment]
You need either to bind it in `shared` scope (an extension) or use `shared_config` to override default behavior from `singleton` to `shared`.
Of course nothing stops you from doing both.

Here is an [example](https://github.com/boost-experimental/di/blob/4767207694ceba58b7655805193249d54e3bf405/extension/test/scopes/shared.cpp#L65)

**Comment by subbota-a** [comment]
Hi, @kanstantsin-chernik !
I was a bug in my example! I wrote 
`di::injector<client>` 
instead of 
`di::injector<shared_ptr<server>>` 
I just wonder why does the injector create me a server though
