### ISSUE TITLE
Singleton scope creates global singleton instead of per injector

### ISSUE THREAD

**Issue by andreasdamm** [boost-ext/di#459]
## Expected Behavior
```c++
auto Bind()
{
    return di::make_injector(
            di::bind<int>.in(di::singleton));
}

int main()
{
    auto inj1 = Bind();
    auto inj2 = Bind();

    auto i1 = inj1.create<shared_ptr<int>>();
    auto i2 = inj2.create<shared_ptr<int>>();

    auto different = i1.get() != i2.get();
    assert(different);

    return 0;
}
```
## Actual Behavior
Assertion fails.

## Steps to Reproduce the Problem

  1. Create two injectors of the same type containing a singleton scoped binding
  1. Have each injector create a shared_ptr of that singleton object
  1. Both shared_ptr's will point to same address

## Specifications

  - Version: 1.1.0
  - Platform: Windows (MSVC)
  - Subsystem: Windows

**Comment by kris-jusiak** [comment]
Duplicate -> https://github.com/boost-experimental/di/issues/431
