### ISSUE TITLE
[Question] New release

### ISSUE THREAD

**Issue by Innokentiy-Alaytsev** [boost-ext/di#477]
Are there any plans for cutting a new (probably minor) release? From [what I can see](https://github.com/boost-experimental/di/compare/v1.1.0...cpp14), many problems were fixed including those preventing from using Boost.DI with the latest version of MSVC.

**Comment by kris-jusiak** [comment]
Yeah, there is, hopefully, very shortly :pray: Was waiting for an update from Microsoft with some bug fixes; will check again :crossed_fingers:

**Comment by Innokentiy-Alaytsev** [comment]
Thanks!

**Comment by kris-jusiak** [comment]
Finally, v1.2.0 got released
* https://github.com/boost-ext/di/releases/tag/v1.2.0

Sorry for the delay but MSVC-2019 updates and GCC-10 took bugs took longer than expected :disappointed:
