### ISSUE TITLE
[Question] inject injector

### ISSUE THREAD

**Issue by hellozyemlya** [boost-ext/di#478]
Is that possible to inject injector?

**Comment by kanstantsin-chernik** [comment]
Yes, although the approach is not perfect (mostly due to C++ rigidness). Take a look at `lazy` extension for example:
https://github.com/boost-experimental/di/blob/cpp14/extension/include/boost/di/extension/injections/lazy.hpp

**Comment by kris-jusiak** [comment]
Yeah, as @kanstantsin-chernik mentions, it's a bit clunky but you can do it with

```cpp
struct ctor {
  using boost_di_inject__ = inject<self<T>>;

  template <class TInjector>
  explicit ctor(const TInjector &);
};
```

Although, please be aware that `ServiceLocator` is an anti-pattern and it's much better to inject dependencies instead :+1: 

You can read more about it here -> https://boost-experimental.github.io/di/
