### ISSUE TITLE
Documentation Site is Down

### ISSUE THREAD

**Issue by Behemyth** [boost-ext/di#479]
## Expected Behavior

https://boost-experimental.github.io/di/ is accessible.

## Actual Behavior

![image](https://user-images.githubusercontent.com/10186991/86173601-373dc800-baee-11ea-9cd6-050c943b4481.png)

**Comment by Behemyth** [comment]
Naturally, this is probably a side effect of the repository ownership change.

**Comment by kris-jusiak** [comment]
Thanks @Behemyth, working on redirection :disappointed: 
The current website page is https://boost-ext.github.io/di/

**Comment by Behemyth** [comment]
Slick work. Thank you for the update.

**Comment by kris-jusiak** [comment]
The official site is now
* https://boost-ext.github.io/di/
