### ISSUE TITLE
Examples won't compile even in Wandbox

### ISSUE THREAD

**Issue by patlecat** [boost-ext/di#497]
## Expected Behavior
Perfect run!
## Actual Behavior
Total failure

Error on Wandbox:
```
Start
terminating with uncaught exception of type std::runtime_error: update
Aborted
Finish
```

**Comment by kris-jusiak** [comment]
Can you elaborate which examples, please?

The following seems to work
* https://wandbox.org/permlink/m6o2of5w6v2yEDoL

**Comment by patlecat** [comment]
Those on the ReadMe page. I simply clicked the links to Wandbox and voilà.

**Comment by kris-jusiak** [comment]
I just check all examples from README and they work as expected.
There is one example in README which shows throw policy -> https://wandbox.org/permlink/mAzJQD8cTwboIxIx, hence the exception.
Closing it, for now, feel free to reopen but please provide a link to examples which aren't working, thanks.
