### ISSUE TITLE
Are you going to release a new version? Add support for C++20 with Visual Studio 2022 generator.

### ISSUE THREAD

**Issue by dmitry-diolan** [boost-ext/di#542]
I see version v1.2.0 was released  Jul 22, 2020 (two years ago).  There are several fixes in the main branch till then.

Are there any plans to make a newer release (tag)? I also see that there is a problem compiling tests and examples with Visual Studio 2022 and specifying c++ version 20 - using CMake and Visual Studio as a generator.
## Expected Behavior
Tests and examples should compile successfully and tests should pass using Visual Studio 2022 generator and specifying C++20
## Actual Behavior
Compilation using Visual Studio 2022 generator and specifying C++20 support fails for some tests and examples.

## Specifications

  - Version: v1.2.0
  - Platform: Windows
  - Subsystem: Visual Studio 2022 generator with C++20 CMAKE_CXX_STANDARD

**Comment by yehorror** [comment]
Hi, this one is actual for me too.
I used to install it via Conan, but it has only v1.2.0 with an issue which was fixed but not yet released. That fact makes it a bit inconvenient to use this way.
Are you planning to publish new release?

**Comment by kris-jusiak** [comment]
https://github.com/boost-ext/di/releases/tag/v1.3.0
