### ISSUE TITLE
Is it possible to implement parent-child scope injectors?

### ISSUE THREAD

**Issue by vrecluse** [boost-ext/di#547]
For example,
If not found in child injector, find in parent injector instead;
When child injector destruct, only destruct the objects in this child scope ;
Multiple children can share a parent injector, shared objects in parent are shared across children;
Arbitary levels of decendents, eg: parent - child - grandchildren scope and more...

**Comment by kanstantsin-chernik** [comment]
Hey, it is absolutely possible. Tale a look at [extensible_injector](https://github.com/boost-ext/di/blob/cpp14/extension/include/boost/di/extension/injections/extensible_injector.hpp). Here is the [test](https://github.com/boost-ext/di/blob/cpp14/extension/test/injections/extensible_injector.cpp) to navigate you

**Comment by vrecluse** [comment]
Greate, Thanks.
