### ISSUE TITLE
Broken links in the documentation

### ISSUE THREAD

**Issue by ldionne** [boost-ext/di#94]
The problem appears on the page http://krzysztof-jusiak.github.io/di/cpp14/boost/libs/di/doc/html/.

Clicking on the "Home", "Libraries" and "More" links at the top right gives me a 404.

**Comment by kris-jusiak** [comment]
fair point, it works only if the library is integrated with boost -> meaning is part of boost libraries.
Anyway fixed it with https://github.com/krzysztof-jusiak/di/commit/c67f25191f63278d5e83f9aa7253df446622f645
