### ISSUE TITLE
Multiple Bindings

### ISSUE THREAD

**Issue by jaime-rq** [boost-ext/di#95]
Hi I am wondering if is possible to have multiple concrete implementations registered to the same interface, and when resolving get a vector<> or list<> of the interface.
This is very useful when implementing a composition pattern. You have multiple providers for a given service and you want to find the one that serve the current need and use that one.

**Comment by kris-jusiak** [comment]
Totally agree that it's very useful and there is `some` support for it, although it's not part of the core library. It's implemented as an example extension here -> https://github.com/krzysztof-jusiak/di/blob/cpp14/example/extensions/container_bindings.cpp. Still require a bit of work, till it will become a proper extension and till will be distributed with the library tho.
